apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-app-dev
resources:
- ../../base
replicas:
- count: 1
  name: demo-app
images:
- digest: sha256:d92d1ef095f9f57c5a3ef23c89759938eff742b7803c41a1bc23676150172ac7
  name: demo-app
  newName: ghcr.io/tarek-gritli/demo-app
