apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-app-dev
resources:
- ../../base
replicas:
- count: 1
  name: demo-app
images:
- digest: sha256:97e3bc5eec38770554245d95140aeaa8d7bbedcdbf24b568b5cd010a5bea45e3
  name: demo-app
  newName: ghcr.io/tarek-gritli/demo-app
