apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-credentials
    namespace: keycloak
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:GrShvCg=,iv:7x2jztGbQBsXWIRglesi+B2c4rqkWm5bOSEESXZhc90=,tag:ECiGO8xDjd/eVJw52+azew==,type:str]
    password: ENC[AES256_GCM,data:Zh0l0u/k3yeYMuqfplrQ2xMDwRzWz9C0,iv:kz3afx2vY5VdEmJxmgdgiZlqAKWUdvnyngB8x4nz8ws=,tag:faCwLr6jcuRE9zmRTDdZDw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZkxPbVlqd0lFMGM0aCtV
            Qk54R0xDZ3ZwYXRKR1BTeEhScUVNbjA3SXhRCitadHkyTGJmT3VOUkhzTExhVXA4
            VWsreklHR2xFQzVaVEVtRk9tVUNyTjAKLS0tIDZuMm5mVTFESTlDZEo5ZUxjUEVx
            eFVITVdVQWsrblFNVUY4QTY1b3MrMWsKixjYDq+Lzw8msbKat3EGWhATULz+fLv7
            HsPw4bunynZrzfHJJuO0K6gGVfICsVf2NVFuWnt8v5865Vx8SD3ajw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g0whd7r6zga2lslajwmrpm7yddkx7rakqth9mf407xv58q7k6arqdxluuq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T18:46:27Z"
    mac: ENC[AES256_GCM,data:iengOttJd7ElUJN3/DBgDGQKm9PoHGqxy05Chbt7lp4QzKBOb5ReJoaFnhiDMdoaTwm5kOmugYfCXFg7qZOURG8UXwVoX3nr59Um8X/hQ9zzGLvQgaRdWADjaxeSWaK1dNpluB+6WnuJULygmDmZWpKWi9F0qVBzwh96GxeJMB8=,iv:wf20AF0CeBDkzpPUqS49Bt8jOSokE6Bc448f+I+8unc=,tag:WFq3RFOb+BPtCjtSgSMX6w==,type:str]
    version: 3.13.3
