apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: keycloak-admin-credentials-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./keycloak-admin-credentials.yaml